# Generated by Django 5.1.7 on 2025-03-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigyasa', '0004_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file_types',
        ),
        migrations.RemoveField(
            model_name='question',
            name='matrix_columns',
        ),
        migrations.RemoveField(
            model_name='question',
            name='matrix_rows',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_file_size',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_labels',
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jigyasa.survey'),
        ),
    ]
